meu_blog/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.dates import ArchiveIndexView
from django.views.generic.base import RedirectView

from blog.models import Article
from blog.feeds import LatestArticles

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', ArchiveIndexView.as_view(model=Article, date_field="pub_date"), name="article_archive"),
    url(r'^rss/$', RedirectView.as_view(url='/rss/latest/')),
    url(r'^rss/latest/$', LatestArticles()),
    url(r'^comments/', include('django.contrib.comments.urls')),
    url(r'blog/', include('blog.urls')),
    url(r'^gallery/', include('gallery.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^bills/', include('bills.urls')),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'login.html'}, 'login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html'}, 'logout'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^change_password/$', 'django.contrib.auth.views.password_change',
        {'template_name': 'change_password.html'},
        name='change_password'),
    url(r'^change_password/success/$', 'django.contrib.auth.views.password_change_done',
        {'template_name': 'change_password_success.html'},
        name='change_password_success'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tags/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('tags.views',
    url(r'^$', 'tags', name='tags'),
    url(r'^(?P<tag_name>.*)/$', 'tag', name='tag'),
)

tags/models.py
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.generic import GenericForeignKey
from django.core.urlresolvers import reverse


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_name': self.name})

    def __unicode__(self):
        return self.name


class ItemTag(models.Model):
    tag = models.ForeignKey('Tag')
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index=True)
    object = GenericForeignKey('content_type', 'object_it')

    class Meta:
        unique_together = ('tag', 'content_type', 'object_id')

tags/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext

from models import Tag


def tags(request):
    list = Tag.objects.all()
    return render_to_response('tags/tags.html',
                              locals(),
                              context_instance=RequestContext(request))


def tag(request, tag_name):
    tag = get_object_or_404(Tag, name=tag_name)
    return render_to_response('tags/tag.html',
                              locals(),
                              context_instance=RequestContext(request))

tags/templates/tags/tag.html
{% extends "base.html" %}

{% block title %}Tag "{{ tag.name }}" - {{ block.super }}{% endblock %}

{% block h1 %}Tag "{{ tag.name }}"{% endblock %}

{% block content %}
<ul>
    {% for item in tag.itemtag_set.all %}
        <li><a href="{{ item.object.get_absolute_url }}">{{ item.object }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

tags/templates/tags/tags.html
{% extends "base.html" %}

{% block title %}Tags -{{ block.super }}{% endblock %}

{% block h1 %}Tags{% endblock %}

{% block content %}
<ul>
    {% for tag in list %}
    <li><a href="{{ tag.get_absolute_url }}">{{ tag }}</a></li>
    {% endfor %}
</ul>
{% endblock content %}

tags/templates/tags/tags_for_object.html
{% load tags_tags %}

<p>
Tags:
{% for tag in object|tags_for_object %}
<a href="{{ tag.get_absolute_url }}">{{ tag }}</a>
{% endfor %}
</p>